[pytest]
addopts = -p no:cacheprovider
python_files = test_*.py
cache_dir = .pytest_cache
norecursedirs =
    .git
    .venv
    venv
    __pycache__
    node_modules
    pytest-cache-files-*
    tmp*
